language: python
python:
    - "2.7"
    - "3.3"
before_install:
    - "export DISPLAY=:99"
    - "sh -e /etc/init.d/xvfb start"
install:
    - "make install"
    - "pip install coveralls"
script:
    - "make cover"
after_success:
    - "coveralls"
